version: '2'
services:
  nginx:
      image: nginx
      restart: always
      ports:
          - "80:8080"
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
