version: '2'
services:
  appserver:
    image: node:6.11.2
    restart: always
    command: node /app/bin/www
    working_dir: /app
    volumes:
      - ./srv:/app
      - ./dist/public:/dist/public
    network_mode: "host"
    environment:
      - listenport=80
    expose:
       - "80"
    ports:
        - "80:80"
