version: '2'
services:
  nginx:
      image: nginx
      restart: always
      expose:
         - "80"
      ports:
          - "80:80"
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      network_mode: "host"
      depends_on:
        - appserver
  appserver:
    image: node:6.11.2
    restart: always
    command: node ./bin/www
    working_dir: /app
    volumes:
      - ./srv:/app
      - ./dist/public:/dist/public
    network_mode: "host"
    environment:
      - listenport=3005
    ports:
       - "3005:3005"
    expose:
       - "3005"
